import React from 'react'
import ReactApexChart from 'react-apexcharts'


function PiChart({pendingCount,completedCount,cancelledCount}) {
    const getChartOptions = () => {
        return {
          series: [pendingCount,completedCount,cancelledCount],
           colors : ["#4CAF50", "#FFC107", "#FF5722"],

          chart: {
            height: 420,
            width: "100%",
            type: "pie",
          },
          stroke: {
            colors: ["white"],
            lineCap: "",
          },
          plotOptions: {
            pie: {
              labels: {
                show: true,
              },
              size: "100%",
              dataLabels: {
                offset: -25
              }
            },
          },
          labels: ["Completed", "Pending", "Cancelled"],
          dataLabels: {
            enabled: true,
            style: {
              fontFamily: "Inter, sans-serif",
            },
          },
          legend: {
            position: "bottom",
            fontFamily: "Inter, sans-serif",
          },
          yaxis: {
            labels: {
              formatter: function (value) {
                return value 
              },
            },
          },
          xaxis: {
            labels: {
              formatter: function (value) {
                return value  
              },
            },
            axisTicks: {
              show: false,
            },
            axisBorder: {
              show: false,
            },
          },
        }
      }
      
      if (document.getElementById("pie-chart") && typeof ApexCharts !== 'undefined') {
        const chart = new ApexCharts(document.getElementById("pie-chart"), getChartOptions());
        chart.render();
      }

      
  return (
    <div className='flex justify-center'>
    <div className="max-w-sm w-full bg-white rounded-lg shadow dark:bg-gray-800 p-4 md:p-6">
  <div className="flex justify-between items-start w-full">
    <div className="flex-col items-center">
      <div className="flex items-center mb-1">
        <h5 className="text-xl font-bold  leading-none text-gray-900 dark:text-white me-1">
          Booking status
        </h5>
        {/* <svg
          data-popover-target="chart-info"
          data-popover-placement="bottom"
          className="w-3.5 h-3.5 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white cursor-pointer ms-1"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="currentColor"
          viewBox="0 0 20 20"
        >
          <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm0 16a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3Zm1-5.034V12a1 1 0 0 1-2 0v-1.418a1 1 0 0 1 1.038-.999 1.436 1.436 0 0 0 1.488-1.441 1.501 1.501 0 1 0-3-.116.986.986 0 0 1-1.037.961 1 1 0 0 1-.96-1.037A3.5 3.5 0 1 1 11 11.466Z" />
        </svg> */}
        <div
          data-popover=""
          id="chart-info"
          role="tooltip"
          className="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400"
        >
          <div className="p-3 space-y-2">
            <h3 className="font-semibold text-gray-900 dark:text-white">
              Activity growth - Incremental
            </h3>
            <p>
              Report helps navigate cumulative growth of community activities.
              Ideally, the chart should have a growing trend, as stagnating
              chart signifies a significant decrease of community activity.
            </p>
            <h3 className="font-semibold text-gray-900 dark:text-white">
              Calculation
            </h3>
            <p>
              For each date bucket, the all-time volume of activities is
              calculated. This means that activities in period n contain all
              activities up to period n, plus the activities generated by your
              community in period.
            </p>
            <a
              href="#"
              className="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700 hover:underline"
            >
              Read more{" "}
              <svg
                className="w-2 h-2 ms-1.5 rtl:rotate-180"
                aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 6 10"
              >
                <path
                  stroke="currentColor"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="m1 9 4-4-4-4"
                />
              </svg>
            </a>
          </div>
          <div data-popper-arrow="" />
        </div>
      </div>

    </div>
 
  </div>
  {/* pie Chart */}
  <div className="py-6" id="pie-chart" />
  <div className="grid grid-cols-1 items-center border-gray-200 border-t dark:border-gray-700 justify-between">
    <div className="flex justify-between items-center pt-5">
      {/* Button */}
      {/* <button
        id="dropdownDefaultButton"
        data-dropdown-toggle="lastDaysdropdown"
        data-dropdown-placement="bottom"
        className="text-sm font-medium text-gray-500 dark:text-gray-400 hover:text-gray-900 text-center inline-flex items-center dark:hover:text-white"
        type="button"
      >
        Last 7 days
        <svg
          className="w-2.5 m-2.5 ms-1.5"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 10 6"
        >
          <path
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="m1 1 4 4 4-4"
          />
        </svg>
      </button> */}
      {/* <div
        id="lastDaysdropdown"
        className="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700"
      >
        <ul
          className="py-2 text-sm text-gray-700 dark:text-gray-200"
          aria-labelledby="dropdownDefaultButton"
        >
          <li>
            <a
              href="#"
              className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
            >
              Yesterday
            </a>
          </li>
          <li>
            <a
              href="#"
              className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
            >
              Today
            </a>
          </li>
          <li>
            <a
              href="#"
              className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
            >
              Last 7 days
            </a>
          </li>
          <li>
            <a
              href="#"
              className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
            >
              Last 30 days
            </a>
          </li>
          <li>
            <a
              href="#"
              className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
            >
              Last 90 days
            </a>
          </li>
        </ul>
      </div> */}
     
    </div>
  </div>
</div>
</div>
  )
}

export default PiChart
